### PR TITLE
Replaced doubles in com.caverock.androidsvg.SVGAndroidRenderer#arcTo() with floats

### PR DESCRIPTION
**Pull request by ndahlquist**
Closes https://github.com/BigBadaboom/androidsvg/issues/62.

Only a workaround, so would understand if you don't want to merge, but this fixes the crash we were seeing.

### CODE REVIEW

**Comment by BigBadaboom** [comment]
Sorry for ignoring you Nic. I forgot to turn Watch on for this repo.

Floats may well be okay.  When I get a sec, I'll experiment and see if breaks any corner cases.

**Comment by BigBadaboom** [comment]
Closing. I added patch manually.

**Comment by mmshaul** [comment]
On line 2632 there's still a double that wasn't changed to a float - was this intentional?

**Comment by BigBadaboom** [comment]
Are you referring to the line with `Math.toDegrees()`?  It's line 2673 for me.

Whether it was deliberate or not, I can't say, since it was a patch from a user.  But it is only a temp var holding a return value from `Math.toDegrees()`, which is a `double`. There is no reason to cast it to a float, since it only gets manipulated a little then passed to another method.

**Pull request closed without merging**
